# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight UTC
  # Optional: Uncomment the lines below to also run on push and pull_request events
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mark stale issues and PRs
        uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: 30  # Issues inactive for 30 days will be labeled as stale
          days-before-pr-stale: 30    # PRs inactive for 30 days will be labeled as stale
          days-before-close: 7        # Stale issues and PRs will be closed after 7 days
          stale-issue-message: 'This issue has been inactive for 30 days and is now marked as stale.'
          stale-pr-message: 'This pull request has been inactive for 30 days and is now marked as stale.'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-issues: '.*(dependabot|renovate).*'  # Exempt issues with dependabot or renovate in the title
          exempt-pull-requests: '.*(dependabot|renovate).*'  # Exempt PRs with dependabot or renovate in the title
